CXX=g++

CFLAGS=-I/home/komatsu/opt/rose-0.9.5a/include -I/home/komatsu/opt/boost-1.47/include
LDIR =-L/home/komatsu/opt/rose-0.9.5a/lib -L/home/komatsu/opt/rose-0.9.5a/lib
LIBS = -lrose

OBJS = autoOMP_f.o

TARGET = autoOMP

%.o: %.C $(DEPS)
	$(CXX) -c -o $@ $< $(CFLAGS)

$(TARGET): $(OBJS)
	$(CXX) -o $@ $^ $(CFLAGS) $(LDIR) $(LIBS)

.PHONY: clean

clean:
	rm -f *.o *~ core

